Transform: 'AWS::Serverless-2016-10-31'

Resources:

  DynamoDBTable1:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: 'table-name-one'
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: hash
          AttributeType: S
        - AttributeName: range
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: hash
          KeyType: HASH
        - AttributeName: range
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: id-index
          KeySchema:
            - AttributeName: id
              KeyType: HASH
          Projection:
            ProjectionType: ALL

            
Outputs:
  TableName:
    Description: The first table
    Value:  !Ref DynamoDBTable1
    Export: # This is the name exported by this template and importable elsewhere
      Name: sam-table-name-export

