Transform: 'AWS::Serverless-2016-10-31'

Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: 'table-name-nn-one'
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: hash
          AttributeType: S
        - AttributeName: range
          AttributeType: S
        - AttributeName: objid
          AttributeType: S
      KeySchema:
        - AttributeName: hash
          KeyType: HASH
        - AttributeName: range
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: objid-index
          KeySchema:
            - AttributeName: objid
              KeyType: HASH
          Projection:
            ProjectionType: ALL
            
Outputs:
  TableName:
    Description: The table
    Value:  !Ref DynamoDBTable
    Export: # This is the name exported by this template and importable elsewhere
      Name: sam-table-name-export2

